services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
